import assert from 'node:assert/strict';
import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import type { TestContext } from 'node:test';
import { runInNewContext } from 'node:vm';
import { chromium, type Browser, type BrowserContext, type Page } from 'playwright';
import { initialData, type CrmData } from '../models.js';
import { installA35H5R1ModernTenantHarness } from './a35-h5-r1-modern-tenant-harness.js';

const userId = 'block4-extension-import-user';
interface SelectMetric { name:string;color:string;background:string;ratio:number;optionRatio:number;disabledRatio:number; }

function browserCrm(): CrmData {
  const crm=structuredClone(initialData);
  crm.organization={id:'block4-extension-import-org',name:'Inmobiliaria Import Test',seatLimit:null,planLabel:'Block 4 hardening'};
  crm.teamMembers=[{id:1,userId,name:'Corredor Import Test',email:'import@example.test',role:'Dueño',status:'Activo',createdAt:'2026-09-21T12:00:00.000Z'}];
  crm.clients=[];crm.properties=[];crm.visits=[];crm.offers=[];crm.reservations=[];crm.contacts=[];crm.reminders=[];crm.fichas=[];crm.conversations=[];crm.activityLog=[];
  crm.settings={...crm.settings,profileName:'Corredor Import Test',profileEmail:'import@example.test',agencyName:'Inmobiliaria Import Test'};
  return crm;
}
function chromeExecutable(): string|undefined { return ['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'].find(existsSync); }
async function waitForServer(baseUrl:string):Promise<void>{let last:unknown;for(let i=0;i<80;i+=1){try{const r=await fetch(baseUrl+'/health');if(r.ok)return;}catch(e){last=e;}await new Promise(r=>setTimeout(r,250));}throw new Error('Servidor Block 4 no disponible: '+String(last??'sin respuesta'));}
async function startServer(port:number):Promise<ChildProcess>{const s=spawn(process.execPath,['dist/server.js'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),SUPABASE_URL:'',SUPABASE_PUBLISHABLE_KEY:'',SUPABASE_SECRET_KEY:'',SUPABASE_SERVICE_ROLE_KEY:'',LEAD_QUALIFICATION_AI_ENDPOINT:'',LEAD_QUALIFICATION_AI_KEY:'',LEAD_QUALIFICATION_AI_MODEL:''},stdio:['ignore','pipe','pipe']});await waitForServer('http://127.0.0.1:'+port);return s;}
async function stopServer(s:ChildProcess):Promise<void>{if(s.exitCode!==null)return;s.kill('SIGTERM');await new Promise<void>(resolve=>{const timer=setTimeout(()=>{if(s.exitCode===null)s.kill('SIGKILL');resolve();},2000);s.once('exit',()=>{clearTimeout(timer);resolve();});});}
async function createAuthedContext(browser:Browser,viewport:{width:number;height:number}):Promise<BrowserContext>{const context=await browser.newContext({viewport,locale:'es-AR'});await installA35H5R1ModernTenantHarness(context,browserCrm(),userId);await context.addInitScript(({actorUserId})=>{localStorage.setItem('propcontrol-cloud-session-v1',JSON.stringify({accessToken:'block4-extension-import-token',refreshToken:'block4-extension-import-refresh',expiresAt:Date.now()+3600000,userId:actorUserId,email:'import@example.test'}));localStorage.setItem('propcontrol-active-team-member-v1','1');},{actorUserId:userId});return context;}
function importPayload(price='USD 125.000'){return{success:true,provider:'zonaprop',sourceUrl:'https://www.zonaprop.com.ar/propiedades/departamento-importado.html',warnings:[],data:{title:'Departamento importado en Nueva Córdoba',propertyType:'Departamento',operation:'Venta',zone:'Nueva Córdoba, Córdoba',price,bedrooms:'2',bathrooms:'1',garage:'1 cochera cubierta',coveredMeters:'70 m²',totalMeters:'80 m²',age:'10 años',status:'Activa',deed:'Sí',creditReady:'Sí',paymentMethod:'Contado',amenities:'Balcón, cochera, pileta',description:'Departamento real de dos dormitorios con balcón y cochera.',photoUrls:['https://img.example.com/1.jpg','javascript:alert(1)','https://img.example.com/2.jpg','https://img.example.com/3.jpg','https://img.example.com/4.jpg','https://img.example.com/5.jpg','https://img.example.com/6.jpg','https://img.example.com/7.jpg','https://img.example.com/8.jpg','https://img.example.com/9.jpg','notaurl']}};}
function parseColor(value:string):[number,number,number]{const m=value.match(/rgba?\(([^)]+)\)/);assert.ok(m?.[1],'Color no interpretable: '+value);const p=m[1].split(/[ ,/]+/).filter(Boolean).map(Number);return[p[0]??0,p[1]??0,p[2]??0];}
function contrastRatio(f:string,b:string):number{const ch=(v:number)=>{const n=v/255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;};const l=(r:[number,number,number])=>.2126*ch(r[0])+.7152*ch(r[1])+.0722*ch(r[2]);const a=l(parseColor(f)),c=l(parseColor(b));return(Math.max(a,c)+.05)/(Math.min(a,c)+.05);}
async function selectMetrics(page:Page):Promise<SelectMetric[]>{const raw=await page.locator('#propiedades #mvp-property-form select').evaluateAll(selects=>selects.map(node=>{const s=node as HTMLSelectElement;const normal=getComputedStyle(s);const option=s.options[0]?getComputedStyle(s.options[0]):normal;const snapshot={name:String(s.name),color:String(normal.color),background:String(normal.backgroundColor),optionColor:String(option.color),optionBackground:String(option.backgroundColor)};s.disabled=true;const disabled=getComputedStyle(s);const disabledSnapshot={color:String(disabled.color),background:String(disabled.backgroundColor)};s.disabled=false;return{...snapshot,disabled:disabledSnapshot};}));return raw.map(m=>({name:m.name,color:m.color,background:m.background,ratio:contrastRatio(m.color,m.background),optionRatio:contrastRatio(m.optionColor,m.optionBackground),disabledRatio:contrastRatio(m.disabled.color,m.disabled.background)}));}
async function assertSelectAccessibility(page:Page,label:string):Promise<SelectMetric[]>{const expected=['type','operation','deed','creditReady','status'];const metrics=(await selectMetrics(page)).filter(m=>expected.includes(m.name));assert.deepEqual(metrics.map(m=>m.name),expected,label+': selects');for(const m of metrics){assert.ok(m.ratio>=4.5,label+' '+m.name+'='+m.ratio.toFixed(2));assert.ok(m.optionRatio>=4.5,label+' option '+m.name+'='+m.optionRatio.toFixed(2));assert.ok(m.disabledRatio>=4.5,label+' disabled '+m.name+'='+m.disabledRatio.toFixed(2));}const first=page.locator('#propiedades #mvp-property-form select[name="type"]');await first.focus();const focus=await first.evaluate(node=>{const s=getComputedStyle(node);return{style:s.outlineStyle,width:s.outlineWidth};});assert.notEqual(focus.style,'none');assert.notEqual(focus.width,'0px');return metrics;}
function runBackgroundSufficiencyMatrix():void{const source=readFileSync('extension/trv-fichas-chrome/background.js','utf8');const sandbox:Record<string,unknown>={URL,setTimeout,clearTimeout,fetch:async()=>({ok:true}),importScripts:()=>undefined,chrome:{runtime:{onMessage:{addListener:()=>undefined}}}};sandbox.globalThis=sandbox;runInNewContext(source+'\n;globalThis.__block4Sufficient = hasSufficientPropertyData;',sandbox);const sufficient=sandbox.__block4Sufficient as ((data:Record<string,unknown>)=>boolean)|undefined;assert.equal(typeof sufficient,'function');for(const data of[{title:'Departamento aislado',photoUrls:[]},{title:'www.zonaprop.com.ar',photoUrls:[]},{title:'Just a moment...',description:'Checking your browser before accessing the site.',photoUrls:[]},{title:'CAPTCHA',photoUrls:[]},{title:'Access denied',photoUrls:[]},{title:'Cloudflare verification',photoUrls:[]}])assert.equal(sufficient!(data),false,JSON.stringify(data));assert.equal(sufficient!({title:'Departamento 2 dormitorios en Nueva Córdoba',price:'USD 125000',zone:'Nueva Córdoba',photoUrls:['https://img.example.com/depto.jpg']}),true);}
async function assertHttpSingleUseAndGuard(baseUrl:string):Promise<void>{const headers={'Content-Type':'application/json','X-TRV-Extension':'1'},sourceUrl='https://www.zonaprop.com.ar/propiedades/departamento-real.html';for(const data of[{title:'Solo title',photoUrls:[]},{title:'www.zonaprop.com.ar',photoUrls:[]},{title:'CAPTCHA',photoUrls:[]},{title:'Access denied',photoUrls:[]},{title:'Cloudflare verification',photoUrls:[]}]){const rejected=await fetch(baseUrl+'/api/extension-import',{method:'POST',headers,body:JSON.stringify({sourceUrl,data})});assert.equal(rejected.status,400,JSON.stringify(data));}const created=await fetch(baseUrl+'/api/extension-import',{method:'POST',headers,body:JSON.stringify({sourceUrl,data:{title:'Departamento real en Nueva Córdoba',price:'USD 125000',zone:'Nueva Córdoba',photoUrls:['https://img.example.com/real.jpg']}})});assert.equal(created.status,201);const body=await created.json() as {success?:boolean;token?:string};assert.equal(body.success,true);assert.ok(body.token);const first=await fetch(baseUrl+'/api/extension-import/'+body.token);assert.equal(first.status,200);assert.equal((await first.json() as {success?:boolean}).success,true);assert.equal((await fetch(baseUrl+'/api/extension-import/'+body.token)).status,404);}
async function installImportRoute(context:BrowserContext,gate?:Promise<void>):Promise<void>{await context.route('**/api/extension-import/*',async route=>{const token=decodeURIComponent(new URL(route.request().url()).pathname.split('/').pop()||'');if(token==='main-token'&&gate)await gate;if(token==='error-token'){await route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({success:false,error:'Importación sintética rechazada.'})});return;}const price=token==='eur-token'?'EUR 125000':token==='plain-token'?'125000':'USD 125.000';await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(importPayload(price))});});}
async function priceMatrix(page:Page){const cases=['USD 125000','USD 125.000','USD 125,000','U$S 125.000','US$ 125,000','ARS 125000','$ 125.000','EUR 125000','BRL 125000','125000'];return page.evaluate(async values=>{const path='/dist/extension-import-ui.js';const mod=await import(path) as {importedUsdPrice:(value:string)=>number|undefined};return values.map(raw=>({raw,value:mod.importedUsdPrice(raw)??null}));},cases);}
async function assertImportedForm(page:Page):Promise<void>{const expected:Record<string,string>={title:'Departamento importado en Nueva Córdoba',address:'Nueva Córdoba, Córdoba',type:'Departamento',operation:'Venta',price:'125000',status:'Activa',bedrooms:'2',bathrooms:'1',garage:'1 cochera cubierta',coveredMeters:'70',totalMeters:'80',age:'10 años',deed:'Sí',creditReady:'Sí',paymentMethod:'Contado',features:'Balcón, cochera, pileta',description:'Departamento real de dos dormitorios con balcón y cochera.',sourceLink:'https://www.zonaprop.com.ar/propiedades/departamento-importado.html'};for(const[name,value]of Object.entries(expected))assert.equal(await page.locator('#mvp-property-form [name="'+name+'"]').inputValue(),value,name);const storage=await page.locator('#mvp-property-form textarea[name="photoUrls"]').inputValue(),photos=storage.split(/\r?\n/).filter(Boolean);assert.equal(photos.length,8);assert.ok(photos.every(url=>/^https?:\/\//.test(url)));assert.doesNotMatch(storage,/javascript:|notaurl/);assert.equal(await page.locator('#mvp-property-form .mvp-property-photo-item').count(),8);assert.match((await page.locator('#mvp-property-form [data-property-photo-count]').textContent())||'',/8 de 8 fotos/);}

export async function runExtensionImportHardening(_t:TestContext):Promise<void>{
  runBackgroundSufficiencyMatrix();
  const port=4587,base='http://127.0.0.1:'+port,server=await startServer(port);
  try{
    await assertHttpSingleUseAndGuard(base);
    const executable=chromeExecutable();
    if(!executable){if(process.env.GITHUB_ACTIONS==='true')assert.fail('GitHub Actions no expone Chrome/Chromium para Block 4.');console.log('BLOCK4_BROWSER_QA_SKIPPED=no Chrome/Chromium local');return;}
    const browser=await chromium.launch({executablePath:executable,headless:true,args:['--no-sandbox']});
    try{
      let release:(()=>void)|undefined;const gate=new Promise<void>(r=>{release=r;});
      const desktop=await createAuthedContext(browser,{width:1366,height:768});await installImportRoute(desktop,gate);const page=await desktop.newPage();const uploads:string[]=[];
      page.on('request',request=>{if(request.method()==='POST'&&new URL(request.url()).pathname==='/api/property-photos')uploads.push(request.url());});
      try{
        await page.goto(base+'/#extension-import=main-token',{waitUntil:'domcontentloaded'});
        await page.waitForSelector('#propiedades.active #mvp-property-form:not(.collapsed)',{state:'visible',timeout:20000});
        assert.equal(await page.evaluate(async()=>{const path='/dist/store.js';const s=await import(path) as {state:{crm:{properties:unknown[]}}};return s.state.crm.properties.length;}),0);
        await page.evaluate(()=>{const w=window as Window&{__block4TenantWrites?:number};w.__block4TenantWrites=0;const native=Storage.prototype.setItem;Storage.prototype.setItem=function(k:string,v:string){if(k.includes('trv-crm-basico:user:'))w.__block4TenantWrites=(w.__block4TenantWrites??0)+1;native.call(this,k,v);};});
        assert.deepEqual(await priceMatrix(page),[{raw:'USD 125000',value:125000},{raw:'USD 125.000',value:125000},{raw:'USD 125,000',value:125000},{raw:'U$S 125.000',value:125000},{raw:'US$ 125,000',value:125000},{raw:'ARS 125000',value:null},{raw:'$ 125.000',value:null},{raw:'EUR 125000',value:null},{raw:'BRL 125000',value:null},{raw:'125000',value:null}]);
        release?.();await page.waitForFunction(()=>document.querySelector('[data-property-import-status] strong')?.textContent?.includes('Propiedad importada'));
        assert.equal((await page.locator('#propiedades').getAttribute('class'))?.includes('active'),true);assert.equal((await page.locator('#crm').getAttribute('class'))?.includes('active'),false);await assertImportedForm(page);assert.equal(new URL(page.url()).hash,'');
        assert.equal(await page.evaluate(async()=>{const path='/dist/store.js';const s=await import(path) as {state:{crm:{properties:unknown[]}}};return s.state.crm.properties.length;}),0);
        await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>(window as Window&{__block4TenantWrites?:number}).__block4TenantWrites??0),0);assert.deepEqual(uploads,[]);
        console.log('BLOCK4_SELECT_DESKTOP='+JSON.stringify(await assertSelectAccessibility(page,'desktop')));
        for(const token of ['eur-token','plain-token']){const currencyPage=await desktop.newPage();try{await currencyPage.goto(base+'/#extension-import='+token,{waitUntil:'domcontentloaded'});await currencyPage.waitForFunction(()=>document.querySelector('[data-property-import-status]')?.textContent?.includes('no está expresado claramente en USD'));assert.equal(await currencyPage.locator('#mvp-property-form [name="price"]').inputValue(),'');assert.equal(new URL(currencyPage.url()).hash,'');}finally{await currencyPage.close();}}
      }finally{await page.close();await desktop.close();}

      const mobile=await createAuthedContext(browser,{width:390,height:844});await installImportRoute(mobile);const mp=await mobile.newPage();
      try{await mp.goto(base+'/#extension-import=mobile-token',{waitUntil:'domcontentloaded'});await mp.waitForFunction(()=>document.querySelector('[data-property-import-status] strong')?.textContent?.includes('Propiedad importada'));console.log('BLOCK4_SELECT_MOBILE='+JSON.stringify(await assertSelectAccessibility(mp,'mobile-390')));}finally{await mp.close();await mobile.close();}

      const unauth=await browser.newContext({viewport:{width:390,height:844},locale:'es-AR'});const up=await unauth.newPage();
      try{await up.goto(base+'/#extension-import=auth-token',{waitUntil:'domcontentloaded'});await up.waitForSelector('#public-auth-form',{state:'visible',timeout:20000});const u=new URL(up.url());assert.equal(u.pathname,'/login');assert.equal(u.hash,'#extension-import=auth-token');}finally{await up.close();await unauth.close();}

      const auth=await createAuthedContext(browser,{width:390,height:844});await installImportRoute(auth);const ap=await auth.newPage();
      try{
        await ap.goto(base+'/login#extension-import=auth-token',{waitUntil:'domcontentloaded'});await ap.waitForFunction(()=>document.querySelector('[data-property-import-status] strong')?.textContent?.includes('Propiedad importada'));const u=new URL(ap.url());assert.equal(u.pathname,'/');assert.equal(u.hash,'');
        const errorPage=await auth.newPage();
        try{await errorPage.goto(base+'/#extension-import=error-token',{waitUntil:'domcontentloaded'});await errorPage.waitForFunction(()=>location.hash==='');const errorUrl=new URL(errorPage.url());assert.equal(errorUrl.hash,'');const notice=errorPage.locator('#notice');await notice.waitFor({state:'visible',timeout:20000});assert.match((await notice.textContent())||'',/Importación sintética rechazada\./);assert.equal((await errorPage.locator('#propiedades').getAttribute('class'))?.includes('active'),true);assert.equal(await errorPage.locator('#mvp-property-form:not(.collapsed)').count(),1);}finally{await errorPage.close();}
      }finally{await ap.close();await auth.close();}
    }finally{await browser.close();}
  }finally{await stopServer(server);}
}
