import assert from 'node:assert/strict';
import { spawn, type ChildProcess } from 'node:child_process';
import { existsSync } from 'node:fs';
import test from 'node:test';
import { chromium, type BrowserContext, type Page } from 'playwright';
import { initialData, type CrmData, type TeamMember } from '../models.js';

const USER='p1-a6-owner', KEY=`trv-crm-basico:user:${USER}`;
function owner():TeamMember{return{id:1,userId:USER,name:'Franco Solis',email:'franco@propcontrol.test',role:'Dueño',status:'Activo',createdAt:'2026-08-25T12:00:00.000Z'};}
function fixture():CrmData{const x=structuredClone(initialData);x.organization={id:'p1-a6-org',name:'TRV',seatLimit:null,planLabel:'A6'};x.teamMembers=[owner()];x.clients=[{id:1,name:'Lucía Martín',phone:'351',interest:'Dúplex',status:'Lead',temperature:'Caliente',pipeline:'Negociación',assignedToId:1,createdById:1}];x.properties=[{id:10,title:'Docta Etapa 3',address:'Córdoba',type:'Dúplex',operation:'Venta',price:100000,owner:'Constructor',status:'Activa',assignedToId:1,createdById:1}];x.offers=[{id:20,clientId:1,propertyId:10,origin:'Cliente',amount:75000,currency:'USD',status:'Pendiente',assignedToId:1,createdById:1,createdAt:'2026-08-25T12:00:00.000Z',updatedAt:'2026-08-25T12:00:00.000Z'}];x.visits=[];x.reservations=[];x.reminders=[];x.activityLog=[];x.contacts=[];x.conversations=[];x.fichas=[];return x;}
function chrome():string|undefined{return['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium'].find(existsSync);}
async function server(port:number):Promise<ChildProcess>{const child=spawn(process.execPath,['dist/server.js'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),SUPABASE_URL:'',SUPABASE_PUBLISHABLE_KEY:'',SUPABASE_SECRET_KEY:'',SUPABASE_SERVICE_ROLE_KEY:''},stdio:'ignore'});for(let i=0;i<120;i++){try{if((await fetch(`http://127.0.0.1:${port}/health`)).ok)return child;}catch{}await new Promise((r)=>setTimeout(r,250));}throw new Error('Servidor A6 no disponible');}
async function stop(child:ChildProcess):Promise<void>{if(child.exitCode===null)child.kill('SIGTERM');}
async function seed(context:BrowserContext):Promise<void>{await context.addInitScript(({crm,key})=>{localStorage.setItem('propcontrol-cloud-session-v1',JSON.stringify({accessToken:'a',refreshToken:'r',expiresAt:Date.now()+3600000,userId:'p1-a6-owner',email:'franco@propcontrol.test'}));localStorage.setItem(key,JSON.stringify(crm));localStorage.setItem(`${key}:sync`,JSON.stringify({dirty:false,localUpdatedAt:'2026-08-25T12:00:00.000Z',lastCloudSavedAt:'2026-08-25T12:00:00.000Z',lastCloudVersion:'2026-08-25T12:00:00.000Z'}));localStorage.setItem('propcontrol-active-team-member-v1','1');},{crm:fixture(),key:KEY});}
function date(days:number):string{const x=new Date();x.setHours(12,0,0,0);x.setDate(x.getDate()+days);return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;}
async function open(page:Page,url:string):Promise<void>{await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForSelector('.mvp-lead-card[data-client-id="1"]');const sheet=page.locator('[data-lead-full-sheet="1"]');if(!(await sheet.evaluate((x)=>(x as HTMLDetailsElement).open))){const actions=page.locator('.mvp-lead-card[data-client-id="1"] .mvp-lead-actions-menu');await actions.locator(':scope > summary').click();await actions.getByRole('button',{name:'Ver detalles',exact:true}).click();}await page.waitForSelector('[data-lead-reservations="1"]',{state:'visible'});}
async function create(page:Page):Promise<void>{const details=page.locator('[data-lead-reservations="1"] [data-reservation-disclosure]');await details.locator(':scope > summary').click();const form=details.locator('[data-register-reservation="1"]');await form.locator('select[name="offerId"]').selectOption('20');await form.locator('input[name="amount"]').fill('5000');await form.locator('input[name="paymentMethod"]').fill('Transferencia');await form.locator('input[name="reservedAt"]').fill(date(0));await form.locator('input[name="expiresAt"]').fill(date(5));await form.locator('button[type="submit"]').click();await page.waitForFunction(async()=>((await import('/dist/store.js')).state.crm.reservations.length===1));}

test('P1.1-A6 browser registra, muestra y concreta una reserva sin mutar Offer ni crear Reminder',async()=>{const child=await server(48261);const browser=await chromium.launch({headless:true,executablePath:chrome()});const context=await browser.newContext({viewport:{width:1366,height:900}});try{await seed(context);const page=await context.newPage();await open(page,'http://127.0.0.1:48261');await create(page);const sections=page.locator('[data-lead-reservations="1"]');assert.equal(await sections.count(),1);const row=page.locator('[data-reservation-id="1"]');assert.match(await row.textContent()||'',/Docta Etapa 3.*USD.*5[.,]000.*Activa/s);await page.evaluate(async()=>{document.dispatchEvent(new CustomEvent('trv-render'));await new Promise<void>((resolve)=>queueMicrotask(resolve));});assert.equal(await sections.count(),1);const form=page.locator('[data-reservation-id="1"] [data-update-reservation="1"]');await form.locator('select[name="status"]').selectOption('Concretada');await form.locator('button').click();await page.waitForFunction(async()=>((await import('/dist/store.js')).state.crm.reservations[0]?.status==='Concretada'));assert.equal(await sections.count(),1);const data=await page.evaluate(async()=>{const crm=(await import('/dist/store.js')).state.crm;return{crm,offer:crm.offers[0]};});assert.equal(data.crm.clients[0]?.pipeline,'Reservado');assert.notEqual(data.crm.clients[0]?.pipeline,'Ganado');assert.equal(data.offer?.status,'Pendiente');assert.equal(data.crm.reminders.length,0);assert.deepEqual(data.crm.activityLog.map((x)=>x.action),['Reserva concretada','Reserva registrada']);}finally{await context.close();await browser.close();await stop(child);}});
test('P1.1-A6 browser mobile conserva targets >=44px, historial y cero overflow',async()=>{const child=await server(48262);const browser=await chromium.launch({headless:true,executablePath:chrome()});const context=await browser.newContext({viewport:{width:390,height:844}});try{await seed(context);const page=await context.newPage();await open(page,'http://127.0.0.1:48262');const summary=page.locator('[data-reservation-disclosure] > summary');assert.ok((await summary.boundingBox())!.height>=43.99);await summary.click();const controls=page.locator('[data-register-reservation="1"] input, [data-register-reservation="1"] select, [data-register-reservation="1"] textarea, [data-register-reservation="1"] button');for(let i=0;i<await controls.count();i++)assert.ok((await controls.nth(i).boundingBox())!.height>=43.99);const width=await page.evaluate(()=>({view:document.documentElement.clientWidth,html:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert.ok(width.html<=width.view+1&&width.body<=width.view+1);}finally{await context.close();await browser.close();await stop(child);}});
