// @ts-nocheck
const STORAGE_KEY = 'trv-crm-basico';
const WHATSAPP_NUMBER = '5493515110069';
const FICHA_LEGAL = 'Propiedad sujeta a disponibilidad y confirmación de condiciones al momento de la consulta.';

const initialData = {
  clients: [
    { id: 1, name: 'Lucía Martín', phone: '600 123 456', email: 'lucia@email.com', interest: 'Casa de 2 habitaciones en zona centro', status: 'Lead', temperature: 'Caliente', pipeline: 'Visita posible', lastContact: '2026-07-06', nextFollowUp: '2026-07-09', budget: 'USD 210.000', paymentMethod: 'Crédito preaprobado', purchaseTimeframe: '0-3 meses', purpose: 'Vivir', knowsArea: 'Sí', canMoveForward: 'Sí', objections: 'Quiere buena luz natural', notes: 'Preguntó por documentación y estado de la propiedad.' },
    { id: 2, name: 'Andrés Vega', phone: '611 222 333', email: 'andres@email.com', interest: 'Casa con jardín en zona familiar', status: 'Cliente', temperature: 'Tibio', pipeline: 'Seguimiento', lastContact: '2026-06-28', nextFollowUp: '2026-07-08', budget: 'USD 330.000', paymentMethod: 'Venta previa', purchaseTimeframe: '3-6 meses', purpose: 'Vivir', knowsArea: 'No', canMoveForward: 'No', objections: 'Debe vender antes de comprar', notes: 'Pedir actualización de su operación actual.' },
  ],
  properties: [
    { id: 1, title: 'Casa centro reformada', address: 'Calle Mayor 14', type: 'Casa', operation: 'Venta', price: 210000, owner: 'Andrés Vega', status: 'Activa' },
    { id: 2, title: 'Propiedad comercial en avenida', address: 'Avenida Norte 8', type: 'Comercial', operation: 'Venta', price: 180000, owner: 'Inversiones Alba', status: 'Captación' },
  ],
  reminders: [
    { id: 1, date: '2026-07-13', title: 'Llamar a Lucía', related: 'Casa centro reformada', priority: 'Alta' },
    { id: 2, date: '2026-07-15', title: 'Preparar valoración', related: 'Andrés Vega', priority: 'Media' },
  ],
  fichas: [],
};

const modules = [['inicio', 'Inicio'], ['crm', 'CRM / Leads'], ['propiedades', 'Propiedades'], ['fichas', 'Fichas TRV'], ['whatsapp', 'WhatsApp + IA'], ['agenda', 'Agenda / Seguimiento'], ['reportes', 'Reportes'], ['configuracion', 'Configuración']];
const app = document.querySelector('#root');
const logoPath = '/src/assets/trv-logo.svg';
const today = new Date().toISOString().slice(0, 10);
const loadData = () => ({ ...initialData, ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}') });
let crm = loadData();
let activeModule = location.hash.startsWith('#ficha-') ? 'fichas' : 'inicio';
const openForms = { clients: false, properties: false, reminders: false, fichas: false };
const expandedClients = new Set();
let selectedFichaId = Number(location.hash.replace('#ficha-', '')) || null;
let editingFichaId = null;
let fichaMode = 'manual';

const saveData = () => localStorage.setItem(STORAGE_KEY, JSON.stringify(crm));
const currency = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number(value || 0));
const nextId = (items) => Math.max(0, ...items.map((item) => item.id || 0)) + 1;
const hasValue = (value) => Boolean(String(value || '').trim());
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const isPast = (date) => hasValue(date) && date < today;
const daysSince = (date) => hasValue(date) ? Math.floor((new Date(today) - new Date(date)) / 86400000) : 999;
const publicFichaFields = ['title', 'propertyType', 'operation', 'zone', 'approxAddress', 'price', 'expenses', 'bedrooms', 'bathrooms', 'garage', 'coveredMeters', 'totalMeters', 'age', 'status', 'amenities', 'description', 'deed', 'creditReady', 'paymentMethod'];

app.innerHTML = `
  <main class="app-shell premium-shell">
    <aside class="sidebar premium-sidebar" aria-label="Navegación principal">
      <div class="brand"><img class="brand-logo" src="${logoPath}" alt="Logo TRV Gestión Inmobiliaria"><div><strong>TRV CRM</strong><span>SaaS inmobiliario</span></div></div>
      <nav class="premium-nav">${modules.map(([id, label]) => `<button class="nav-button ${id === activeModule ? 'active' : ''}" data-module="${id}">${label}</button>`).join('')}</nav>
      <div class="sidebar-card"><h3>Semáforo comercial</h3><p>Leads, propiedades, fichas y seguimiento comercial en un tablero premium.</p></div>
    </aside>
    <section class="content premium-content">
      <header class="topbar"><div><span class="eyebrow">TRV Gestión Inmobiliaria</span><h1 id="module-title">Inicio</h1></div><img class="topbar-logo" src="${logoPath}" alt="TRV Gestión Inmobiliaria"><span class="status-badge">Railway ready · localStorage</span></header>
      <section class="module-panel active" id="inicio"><section class="metric-grid" aria-label="Vista general del negocio"><article class="metric-card"><span>Leads nuevos</span><strong id="new-leads-count"></strong></article><article class="metric-card hot"><span>Clientes calientes</span><strong id="hot-clients-count"></strong></article><article class="metric-card urgent"><span>Alertas urgentes</span><strong id="urgent-count"></strong></article><article class="metric-card opportunity"><span>Posibles visitas</span><strong id="visit-count"></strong></article><article class="metric-card pending"><span>Seguimientos vencidos</span><strong id="overdue-count"></strong></article><article class="metric-card"><span>Propiedades activas</span><strong id="active-properties-count"></strong></article></section><section class="dashboard-grid"><article class="panel-card"><div class="panel-heading"><div><span class="eyebrow">Alertas comerciales</span><h2>Prioridad de hoy</h2></div></div><div class="alert-list compact" id="home-alert-list"></div></article><article class="panel-card"><div class="panel-heading"><div><span class="eyebrow">Actividad reciente</span><h2>Últimos movimientos</h2></div></div><div class="activity-list" id="activity-list"></div></article></section></section>
      <section class="module-panel" id="crm"><div class="panel-heading"><div><span class="eyebrow">CRM / Leads</span><h2>Pipeline comercial</h2></div><button class="toggle-form" data-form="clients">Nuevo cliente</button></div><div class="pipeline-strip"><span>Nuevo</span><span>Calificado</span><span>Seguimiento</span><span>Visita posible</span><span>Negociación</span><span>Cerrado</span></div><form class="crm-form client-form collapsed" id="client-form"><input name="name" placeholder="Nombre del cliente o lead" required><input name="phone" placeholder="Teléfono" required><input name="email" type="email" placeholder="Email"><input name="interest" placeholder="Qué busca / zona de interés" required><select name="status"><option>Lead</option><option>Cliente</option><option>Seguimiento</option><option>Cerrado</option></select><select name="temperature"><option>Caliente</option><option>Tibio</option><option>Frío</option></select><select name="pipeline"><option>Nuevo</option><option>Calificado</option><option>Seguimiento</option><option>Visita posible</option><option>Negociación</option><option>Cerrado</option><option>Perdido</option></select><input name="lastContact" type="date" aria-label="Fecha de último contacto"><input name="nextFollowUp" type="date" aria-label="Próximo seguimiento"><input name="budget" placeholder="Presupuesto"><input name="paymentMethod" placeholder="Forma de pago"><input name="purchaseTimeframe" placeholder="Plazo de compra"><select name="purpose"><option>Vivir</option><option>Invertir</option></select><select name="knowsArea"><option>Sí</option><option>No</option></select><select name="canMoveForward"><option>Sí</option><option>No</option></select><input name="objections" placeholder="Objeciones"><textarea name="notes" placeholder="Observaciones"></textarea><button>+ Guardar cliente</button></form><div class="card-list" id="client-list"></div></section>
      <section class="module-panel" id="propiedades"><div class="panel-heading"><div><span class="eyebrow">Propiedades</span><h2>Cartera activa</h2></div><button class="toggle-form" data-form="properties">Nueva propiedad</button></div><form class="crm-form collapsed" id="property-form"><input name="title" placeholder="Nombre de la propiedad" required><input name="address" placeholder="Dirección o zona" required><select name="type"><option>Casa</option><option>Departamento</option><option>Comercial</option><option>Terreno</option></select><select name="operation"><option>Venta</option><option>Captación</option></select><input name="price" type="number" min="0" placeholder="Valor de referencia" required><input name="owner" placeholder="Propietario" required><select name="status"><option>Activa</option><option>Captación</option><option>Reservada</option><option>Cerrada</option></select><button>+ Guardar propiedad</button></form><div class="property-board" id="property-list"></div></section>
      <section class="module-panel" id="fichas"><div class="panel-heading"><div><span class="eyebrow">Fichas TRV</span><h2>Generador de fichas comerciales TRV</h2></div><button class="toggle-form" data-form="fichas">Nueva ficha</button></div><div class="fichas-layout"><section class="panel-card ficha-create"><div class="ficha-mode-tabs"><button class="ficha-mode active" data-mode="manual">Carga manual</button><button class="ficha-mode" data-mode="property">Desde propiedad</button><button class="ficha-mode" data-mode="external">Colega / portal</button></div><form class="crm-form ficha-form collapsed" id="ficha-form"><select name="sourcePropertyId" class="property-source-field"></select><input name="title" placeholder="Título" required><input name="propertyType" placeholder="Tipo de propiedad"><select name="operation"><option>Venta</option><option>Captación</option></select><input name="zone" placeholder="Zona"><input name="approxAddress" placeholder="Dirección aproximada"><input name="price" placeholder="Precio"><input name="expenses" placeholder="Expensas"><input name="bedrooms" placeholder="Dormitorios"><input name="bathrooms" placeholder="Baños"><select name="garage"><option value="">Cochera</option><option>Sí</option><option>No</option></select><input name="coveredMeters" placeholder="Metros cubiertos"><input name="totalMeters" placeholder="Metros totales"><input name="age" placeholder="Antigüedad"><input name="status" placeholder="Estado"><input name="amenities" placeholder="Amenities"><textarea name="description" placeholder="Descripción comercial"></textarea><input name="deed" placeholder="Escritura"><input name="creditReady" placeholder="Apto crédito"><input name="paymentMethod" placeholder="Forma de pago"><textarea name="photoUrls" placeholder="Fotos por URL, una por línea"></textarea><textarea name="internalOriginalLink" class="external-only import-url" placeholder="Pegá el enlace de la propiedad"></textarea><button type="button" class="import-property external-only">Importar automáticamente</button><input name="source" class="external-only" placeholder="Fuente detectada"><div class="import-status external-only" id="import-status"></div><div class="import-photos external-only" id="import-photos"></div><textarea name="internalNotes" placeholder="Observaciones internas"></textarea><button>Guardar ficha TRV</button></form></section><section class="panel-card"><div class="panel-heading"><div><span class="eyebrow">Guardadas</span><h2>Fichas comerciales</h2></div></div><div class="ficha-list" id="ficha-list"></div></section><section class="panel-card ficha-preview-panel"><div class="panel-heading"><div><span class="eyebrow">Vista previa premium</span><h2>Ficha para clientes</h2></div></div><div id="ficha-preview"></div></section></div></section>
      <section class="module-panel" id="whatsapp"><div class="empty-module"><span class="eyebrow">WhatsApp + IA</span><h2>Centro de comunicación WhatsApp + IA</h2><p>Diseño preparado sin conexión real a WhatsApp API.</p><div class="feature-grid"><article>Conversaciones</article><article>Resumen IA</article><article>Respuestas sugeridas</article><article>Audios y mensajes</article></div></div></section>
      <section class="module-panel" id="agenda"><div class="panel-heading"><div><span class="eyebrow">Agenda / Seguimiento</span><h2>Tareas comerciales</h2></div><button class="toggle-form" data-form="reminders">Nuevo recordatorio</button></div><form class="crm-form reminders-form collapsed" id="reminder-form"><input name="date" type="date" required><input name="title" placeholder="Qué hay que hacer" required><input name="related" placeholder="Cliente o propiedad relacionada" required><select name="priority"><option>Alta</option><option>Media</option><option>Baja</option></select><button>+ Guardar recordatorio</button></form><div class="card-list reminder-list" id="reminder-list"></div></section>
      <section class="module-panel" id="reportes"><div class="panel-heading"><div><span class="eyebrow">Reportes</span><h2>Indicadores comerciales</h2></div></div><div class="metric-grid report-grid"><article class="metric-card"><span>Leads recibidos</span><strong>38</strong></article><article class="metric-card"><span>Clientes contactados</span><strong>24</strong></article><article class="metric-card"><span>Visitas posibles</span><strong id="report-visits"></strong></article><article class="metric-card"><span>Operaciones cerradas</span><strong>4</strong></article><article class="metric-card"><span>Tasa de respuesta</span><strong>68%</strong></article></div></section>
      <section class="module-panel" id="configuracion"><div class="panel-heading"><div><span class="eyebrow">Configuración</span><h2>Identidad de la inmobiliaria</h2></div></div><div class="settings-grid"><label>Nombre inmobiliaria<input value="TRV Gestión Inmobiliaria"></label><label>WhatsApp<input value="3515110069"></label><label>Logo TRV<img class="settings-logo" src="${logoPath}" alt="Logo TRV"></label><label>Color principal<input type="color" value="#06364a"></label></div></section>
    </section>
  </main>`;

function formValues(form) { return Object.fromEntries(new FormData(form).entries()); }
function fichaLink(ficha) { return `${location.origin}${location.pathname}#ficha-${ficha.id}`; }
function arrayPhotos(value) { return String(value || '').split('\n').map((url) => url.trim()).filter(Boolean); }
function displayValue(value, consultable = false) { return hasValue(value) ? escapeHtml(value) : consultable ? 'Consultar' : ''; }
function removeItem(collection, id) { crm[collection] = crm[collection].filter((item) => item.id !== Number(id)); if (collection === 'fichas' && selectedFichaId === Number(id)) selectedFichaId = crm.fichas[0]?.id || null; saveData(); render(); }
function trafficLight(client) { const ready = client.temperature === 'Caliente' && hasValue(client.budget) && hasValue(client.paymentMethod) && hasValue(client.purchaseTimeframe) && client.canMoveForward === 'Sí'; const blocked = client.temperature === 'Frío' || !hasValue(client.budget) || !hasValue(client.purchaseTimeframe) || client.canMoveForward === 'No'; if (ready) return { color: 'verde', label: 'Verde' }; if (blocked) return { color: 'rojo', label: 'Rojo' }; return { color: 'amarillo', label: 'Amarillo' }; }
function clientSummary(client) { const light = trafficLight(client); const nextStep = light.color === 'verde' && client.pipeline === 'Visita posible' ? 'Este cliente parece apto para visita. Revisar y aprobar.' : light.color === 'rojo' ? 'Reactivar y completar presupuesto, plazo y capacidad de avance.' : 'Hacer seguimiento y completar datos faltantes.'; return { search: client.interest || 'Sin búsqueda definida', budget: client.budget || 'Sin presupuesto definido', area: client.interest || 'Sin zona/interés cargado', objections: client.objections || client.notes || 'Sin objeciones cargadas', nextStep }; }
function clientAlerts(client) { const alerts = []; if (client.temperature === 'Caliente' && daysSince(client.lastContact) >= 3) alerts.push({ type: 'urgent', title: 'Cliente caliente sin contactar', detail: `${client.name} lleva ${daysSince(client.lastContact)} días sin contacto.` }); if (isPast(client.nextFollowUp)) alerts.push({ type: 'urgent', title: 'Seguimiento vencido', detail: `${client.name} tenía seguimiento el ${client.nextFollowUp}.` }); if (client.status === 'Lead' && daysSince(client.lastContact) >= 5) alerts.push({ type: 'pending', title: 'Lead sin responder', detail: `${client.name} necesita una nueva respuesta comercial.` }); if (client.pipeline === 'Visita posible') alerts.push({ type: 'opportunity', title: 'Posible visita para revisar', detail: 'Este cliente parece apto para visita. Revisar y aprobar.' }); if (client.pipeline === 'Negociación' && trafficLight(client).color === 'verde') alerts.push({ type: 'opportunity', title: 'Posible reserva', detail: `${client.name} está en negociación y puede avanzar.` }); if (daysSince(client.lastContact) >= 30) alerts.push({ type: 'pending', title: 'Cliente viejo para reactivar', detail: `${client.name} lleva ${daysSince(client.lastContact)} días sin contacto.` }); return alerts.map((alert) => ({ ...alert, client })); }
function allAlerts() { return crm.clients.flatMap(clientAlerts); }
function alertCard(alert) { return `<article class="alert-card ${alert.type}"><span>${escapeHtml(alert.title)}</span><h3>${escapeHtml(alert.client.name)}</h3><p>${escapeHtml(alert.detail)}</p><small>${escapeHtml(clientSummary(alert.client).nextStep)}</small></article>`; }
function detailItem(label, value) { return hasValue(value) ? `<span><b>${label}:</b> ${escapeHtml(value)}</span>` : ''; }
function setText(selector, value) { const node = document.querySelector(selector); if (node) node.textContent = value; }
function updateModuleVisibility() { modules.forEach(([id, label]) => { document.querySelector(`#${id}`).classList.toggle('active', id === activeModule); if (id === activeModule) document.querySelector('#module-title').textContent = label; }); document.querySelectorAll('.nav-button').forEach((button) => button.classList.toggle('active', button.dataset.module === activeModule)); }
function updateFormVisibility() { document.querySelector('#client-form').classList.toggle('collapsed', !openForms.clients); document.querySelector('#property-form').classList.toggle('collapsed', !openForms.properties); document.querySelector('#reminder-form').classList.toggle('collapsed', !openForms.reminders); document.querySelector('#ficha-form').classList.toggle('collapsed', !openForms.fichas); document.querySelectorAll('.ficha-mode').forEach((button) => button.classList.toggle('active', button.dataset.mode === fichaMode)); document.querySelector('#ficha-form').dataset.mode = fichaMode; }
function recentActivity() { return [`Nuevo lead cargado: ${crm.clients.at(-1)?.name || 'Sin datos'}`, `Ficha TRV disponible: ${crm.fichas.at(-1)?.title || 'Pendiente de crear'}`, `Propiedad revisada: ${crm.properties[0]?.title || 'Sin datos'}`, `Seguimiento próximo: ${crm.reminders[0]?.title || 'Sin datos'}`]; }
function propertyToFicha(property) { return { title: property.title, propertyType: property.type, operation: property.operation, zone: property.address, approxAddress: property.address, price: property.price ? currency(property.price) : '', status: property.status, description: `Ficha comercial de ${property.title}.`, sourcePropertyId: property.id }; }
function fillFichaForm(ficha = {}) { const form = document.querySelector('#ficha-form'); Object.entries(ficha).forEach(([key, value]) => { if (form.elements[key]) form.elements[key].value = Array.isArray(value) ? value.join('\n') : value; }); }
function fichaFromValues(values) { const fromProperty = values.sourcePropertyId ? propertyToFicha(crm.properties.find((property) => property.id === Number(values.sourcePropertyId)) || {}) : {}; return { ...fromProperty, ...values, photoUrls: arrayPhotos(values.photoUrls), id: editingFichaId || nextId(crm.fichas), createdAt: new Date().toISOString(), mode: fichaMode }; }
function whatsappText(ficha) { const features = [ficha.propertyType, ficha.bedrooms && `${ficha.bedrooms} dorm.`, ficha.bathrooms && `${ficha.bathrooms} baños`, ficha.coveredMeters && `${ficha.coveredMeters} cubiertos`, ficha.totalMeters && `${ficha.totalMeters} totales`].filter(Boolean).join(' · '); return [`Hola, te comparto esta propiedad de TRV Gestión Inmobiliaria:`, ficha.title, ficha.zone && `Zona: ${ficha.zone}`, ficha.operation && `Operación: ${ficha.operation}`, ficha.price && `Precio: ${ficha.price}`, features && `Características: ${features}`, `Ficha: ${fichaLink(ficha)}`, 'Si te interesa, coordinamos una consulta para revisar disponibilidad y condiciones.'].filter(Boolean).join('\n'); }
function copyWhatsapp(ficha) { navigator.clipboard?.writeText(whatsappText(ficha)); }
function shareWhatsapp(ficha) { window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(whatsappText(ficha))}`, '_blank'); }
function publicRows(ficha) { const consultable = ['price', 'expenses', 'deed', 'creditReady', 'paymentMethod']; const labels = { propertyType: 'Tipo', operation: 'Operación', zone: 'Zona', approxAddress: 'Dirección aproximada', price: 'Precio', expenses: 'Expensas', bedrooms: 'Dormitorios', bathrooms: 'Baños', garage: 'Cochera', coveredMeters: 'Metros cubiertos', totalMeters: 'Metros totales', age: 'Antigüedad', status: 'Estado', amenities: 'Amenities', deed: 'Escritura', creditReady: 'Apto crédito', paymentMethod: 'Forma de pago' }; return publicFichaFields.map((key) => key === 'garage' && ficha[key] === 'No' ? '' : displayValue(ficha[key], consultable.includes(key)) ? `<span><b>${labels[key] || key}</b>${displayValue(ficha[key], consultable.includes(key))}</span>` : '').join(''); }
function fichaPreview(ficha) { if (!ficha) return '<p class="empty-state">Elegí o creá una ficha para ver la vista previa premium.</p>'; const photos = (ficha.photoUrls || []).map((url) => `<img src="${escapeHtml(url)}" alt="Foto de ${escapeHtml(ficha.title)}">`).join(''); return `<article class="public-ficha"><header><img src="${logoPath}" alt="Logo TRV"><div><span>TRV Gestión Inmobiliaria</span><h2>${escapeHtml(ficha.title)}</h2></div></header><div class="public-gallery">${photos || '<div class="gallery-placeholder">Galería de fotos TRV</div>'}</div><div class="public-data">${publicRows(ficha)}</div>${hasValue(ficha.description) ? `<p class="public-description">${escapeHtml(ficha.description)}</p>` : ''}<button class="whatsapp-ficha" data-id="${ficha.id}">Consultar por WhatsApp</button><small>${FICHA_LEGAL}</small></article>`; }

function renderFichas() { const selected = crm.fichas.find((ficha) => ficha.id === selectedFichaId) || crm.fichas[0]; if (selected && !selectedFichaId) selectedFichaId = selected.id; document.querySelector('[name="sourcePropertyId"]').innerHTML = '<option value="">Elegir propiedad cargada</option>' + crm.properties.map((property) => `<option value="${property.id}">${escapeHtml(property.title)}</option>`).join(''); document.querySelector('#ficha-list').innerHTML = crm.fichas.map((ficha) => `<article class="ficha-list-card ${ficha.id === selectedFichaId ? 'active' : ''}"><div><h3>${escapeHtml(ficha.title)}</h3><p>${escapeHtml([ficha.zone, ficha.operation, ficha.price].filter(Boolean).join(' · '))}</p></div><div class="ficha-actions"><button class="select-ficha" data-id="${ficha.id}">Ver</button><button class="edit-ficha" data-id="${ficha.id}">Editar</button><button class="duplicate-ficha" data-id="${ficha.id}">Duplicar</button><button class="copy-ficha" data-id="${ficha.id}">Copiar WhatsApp</button><button class="share-ficha" data-id="${ficha.id}">Compartir</button><button class="print-ficha">PDF</button><button class="open-ficha" data-id="${ficha.id}">Link interno</button><button class="delete" data-collection="fichas" data-id="${ficha.id}">×</button></div></article>`).join('') || '<p class="empty-state">Todavía no hay fichas guardadas.</p>'; document.querySelector('#ficha-preview').innerHTML = fichaPreview(selected); }


async function importExternalProperty() {
  const form = document.querySelector('#ficha-form') as HTMLFormElement;
  const status = document.querySelector('#import-status') as HTMLElement;
  const url = String((form.elements.namedItem('internalOriginalLink') as HTMLTextAreaElement).value || '').trim();
  if (!url) { status.textContent = 'Pegá un enlace para importar.'; return; }
  status.textContent = 'Importando automáticamente...';
  try {
    const response = await fetch('/api/import-property', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) });
    const result = await response.json();
    if (!result.success) throw new Error(result.error || 'No pudimos importar automáticamente esta publicación. Podés reintentar o completar los datos manualmente.');
    fillFichaForm({ ...result.data, source: result.provider, internalOriginalLink: url, photoUrls: (result.data.photoUrls || []).join('\n') });
    status.textContent = `Portal detectado: ${result.provider}. Fotografías encontradas: ${(result.data.photoUrls || []).length}. ${(result.warnings || []).join(' ')}`;
    renderImportedPhotos(result.data.photoUrls || []);
  } catch (error) {
    status.textContent = error instanceof Error ? error.message : 'No pudimos importar automáticamente esta publicación. Podés reintentar o completar los datos manualmente.';
  }
}
function renderImportedPhotos(urls: string[]) {
  const target = document.querySelector('#import-photos') as HTMLElement;
  target.innerHTML = urls.map((url, index) => `<button type="button" class="remove-import-photo" data-url="${escapeHtml(url)}"><img src="${escapeHtml(url)}" alt="Foto importada ${index + 1}"><span>Quitar</span></button>`).join('');
}
function removeImportedPhoto(url: string) {
  const field = document.querySelector('[name="photoUrls"]') as HTMLTextAreaElement;
  field.value = field.value.split('\n').filter((item) => item.trim() !== url).join('\n');
  renderImportedPhotos(arrayPhotos(field.value));
}

function render() {
  updateModuleVisibility(); updateFormVisibility();
  const alerts = allAlerts(); const urgent = alerts.filter((alert) => alert.type === 'urgent').length; const visits = alerts.filter((alert) => alert.title === 'Posible visita para revisar').length; const overdue = alerts.filter((alert) => alert.title === 'Seguimiento vencido').length;
  setText('#new-leads-count', crm.clients.filter((client) => client.status === 'Lead').length); setText('#hot-clients-count', crm.clients.filter((client) => client.temperature === 'Caliente').length); setText('#urgent-count', urgent); setText('#visit-count', visits); setText('#overdue-count', overdue); setText('#active-properties-count', crm.properties.filter((property) => property.status !== 'Cerrada').length); setText('#report-visits', visits);
  document.querySelector('#home-alert-list').innerHTML = alerts.length ? alerts.slice(0, 4).map(alertCard).join('') : '<p class="empty-state">No hay alertas comerciales activas.</p>'; document.querySelector('#activity-list').innerHTML = recentActivity().map((item) => `<div class="activity-item"><span></span>${escapeHtml(item)}</div>`).join('');
  document.querySelector('#client-list').innerHTML = crm.clients.map((client) => { const light = trafficLight(client); const summary = clientSummary(client); const expanded = expandedClients.has(client.id); return `<article class="crm-card client-card ${light.color}"><div><div class="client-title"><h3>${escapeHtml(client.name)}</h3><span class="traffic ${light.color}">${light.label}</span></div><div class="client-compact"><span>${escapeHtml(client.temperature || 'Sin temperatura')}</span><span>${escapeHtml(client.pipeline || 'Sin pipeline')}</span><span>${escapeHtml(summary.budget)}</span></div><p class="next-step">${escapeHtml(summary.nextStep)}</p><div class="client-extra ${expanded ? 'expanded' : ''}"><small>${escapeHtml(client.phone)} · ${escapeHtml(client.email || 'Sin email')}</small><div class="client-details">${detailItem('Qué busca', summary.search)}${detailItem('Último contacto', client.lastContact)}${detailItem('Próximo seguimiento', client.nextFollowUp)}${detailItem('Forma de pago', client.paymentMethod)}${detailItem('Plazo', client.purchaseTimeframe)}${detailItem('Uso', client.purpose)}${detailItem('Conoce zona', client.knowsArea)}${detailItem('Puede avanzar', client.canMoveForward)}</div><div class="client-summary"><b>Resumen automático:</b><p>Busca: ${escapeHtml(summary.search)}. Presupuesto: ${escapeHtml(summary.budget)}. Zona/interés: ${escapeHtml(summary.area)}. Objeciones: ${escapeHtml(summary.objections)}. Próximo paso recomendado: ${escapeHtml(summary.nextStep)}</p></div></div></div><div class="card-actions"><span class="pill">${escapeHtml(client.status)}</span><button class="ghost expand-client" data-id="${client.id}">${expanded ? 'Ver menos' : 'Ver más'}</button><button class="delete" data-collection="clients" data-id="${client.id}" aria-label="Eliminar cliente ${escapeHtml(client.name)}">×</button></div></article>`; }).join('') || '<p class="empty-state">Todavía no hay clientes o leads.</p>';
  document.querySelector('#property-list').innerHTML = crm.properties.map((property) => `<article class="property-card"><div><span class="pill">${escapeHtml(property.status)}</span><h3>${escapeHtml(property.title)}</h3><p>${escapeHtml(property.address)} · ${escapeHtml(property.type)}</p><small>Preparada para fotos, ficha técnica y estado comercial.</small></div><strong>${currency(property.price)}</strong><button class="delete" data-collection="properties" data-id="${property.id}" aria-label="Eliminar propiedad ${escapeHtml(property.title)}">×</button></article>`).join('') || '<p class="empty-state">Todavía no hay propiedades.</p>';
  document.querySelector('#reminder-list').innerHTML = crm.reminders.slice().sort((a, b) => a.date.localeCompare(b.date)).map((reminder) => `<article class="crm-card reminder"><time>${escapeHtml(reminder.date)}</time><div><h3>${escapeHtml(reminder.title)}</h3><p>${escapeHtml(reminder.related)}</p></div><span class="pill priority-${reminder.priority.toLowerCase()}">${escapeHtml(reminder.priority)}</span><button class="delete" data-collection="reminders" data-id="${reminder.id}" aria-label="Eliminar recordatorio ${escapeHtml(reminder.title)}">×</button></article>`).join('') || '<p class="empty-state">No hay recordatorios pendientes.</p>';
  renderFichas();
}

const handlers = { 'client-form': (values) => crm.clients.push({ id: nextId(crm.clients), ...values }), 'property-form': (values) => crm.properties.push({ id: nextId(crm.properties), ...values, price: Number(values.price) }), 'reminder-form': (values) => crm.reminders.push({ id: nextId(crm.reminders), ...values }), 'ficha-form': (values) => { const ficha = fichaFromValues(values); const index = crm.fichas.findIndex((item) => item.id === ficha.id); index >= 0 ? crm.fichas.splice(index, 1, ficha) : crm.fichas.push(ficha); selectedFichaId = ficha.id; editingFichaId = null; location.hash = `ficha-${ficha.id}`; } };
Object.entries(handlers).forEach(([formId, handler]) => { document.querySelector(`#${formId}`).addEventListener('submit', (event) => { event.preventDefault(); handler(formValues(event.currentTarget)); event.currentTarget.reset(); const formMap = { 'client-form': 'clients', 'property-form': 'properties', 'reminder-form': 'reminders', 'ficha-form': 'fichas' }; openForms[formMap[formId]] = false; saveData(); render(); }); });

document.querySelector('[name="sourcePropertyId"]').addEventListener('change', (event) => {
  const property = crm.properties.find((item) => item.id === Number(event.target.value));
  if (property) fillFichaForm(propertyToFicha(property));
});
document.addEventListener('click', (event) => { const id = Number(event.target.dataset.id); const ficha = crm.fichas.find((item) => item.id === id); if (event.target.matches('.delete')) removeItem(event.target.dataset.collection, event.target.dataset.id); if (event.target.matches('.nav-button')) { activeModule = event.target.dataset.module; render(); } if (event.target.matches('.toggle-form')) { openForms[event.target.dataset.form] = !openForms[event.target.dataset.form]; render(); } if (event.target.matches('.expand-client')) { expandedClients.has(id) ? expandedClients.delete(id) : expandedClients.add(id); render(); } if (event.target.matches('.ficha-mode')) { fichaMode = event.target.dataset.mode; openForms.fichas = true; render(); } if (event.target.matches('.select-ficha')) { selectedFichaId = id; location.hash = `ficha-${id}`; render(); } if (event.target.matches('.edit-ficha') && ficha) { editingFichaId = id; openForms.fichas = true; fichaMode = ficha.mode || 'manual'; render(); fillFichaForm({ ...ficha, photoUrls: (ficha.photoUrls || []).join('\n') }); } if (event.target.matches('.duplicate-ficha') && ficha) { const copy = { ...ficha, id: nextId(crm.fichas), title: `${ficha.title} (copia)`, createdAt: new Date().toISOString() }; crm.fichas.push(copy); selectedFichaId = copy.id; saveData(); render(); } if (event.target.matches('.copy-ficha') && ficha) copyWhatsapp(ficha); if (event.target.matches('.share-ficha, .whatsapp-ficha') && ficha) shareWhatsapp(ficha); if (event.target.matches('.import-property')) importExternalProperty(); if (event.target.matches('.remove-import-photo')) removeImportedPhoto(event.target.dataset.url || ''); if (event.target.matches('.print-ficha')) window.print(); if (event.target.matches('.open-ficha') && ficha) { location.hash = `ficha-${id}`; selectedFichaId = id; render(); } });
window.addEventListener('hashchange', () => { if (location.hash.startsWith('#ficha-')) { selectedFichaId = Number(location.hash.replace('#ficha-', '')); activeModule = 'fichas'; render(); } });

render();
