import { Client, Temperature } from './models.js';
import { saveData, state } from './store.js';
import { escapeHtml, field, formValues, nextId } from './utils.js';

function trafficLight(client: Client): { color: string; label: string; next: string } {
  const ready = client.temperature === 'Caliente' && client.budget && client.paymentMethod && client.purchaseTimeframe && client.canMoveForward === 'Sí';
  if (ready) return { color: 'verde', label: 'Caliente', next: client.pipeline === 'Visita posible' ? 'Este cliente parece apto para visita. Revisar y aprobar.' : 'Contactar hoy y avanzar.' };
  if (client.temperature === 'Frío' || client.canMoveForward === 'No') return { color: 'rojo', label: 'Frío', next: 'Completar calificación antes de ofrecer visita.' };
  return { color: 'amarillo', label: 'Tibio', next: 'Hacer seguimiento y completar datos faltantes.' };
}

export function renderHome(container: HTMLElement): void {
  const hot = state.crm.clients.filter((client) => client.temperature === 'Caliente').length;
  const visits = state.crm.clients.filter((client) => client.pipeline === 'Visita posible').length;
  const overdue = state.crm.reminders.filter((reminder) => reminder.date < new Date().toISOString().slice(0, 10)).length;
  container.innerHTML = `<div class="metric-grid"><article><span>Leads</span><strong>${state.crm.clients.length}</strong></article><article><span>Calientes</span><strong>${hot}</strong></article><article><span>Visitas posibles</span><strong>${visits}</strong></article><article><span>Seguimientos vencidos</span><strong>${overdue}</strong></article><article><span>Propiedades activas</span><strong>${state.crm.properties.filter((item) => item.status !== 'Cerrada').length}</strong></article><article><span>Fichas TRV</span><strong>${state.crm.fichas.length}</strong></article></div><div class="dashboard-grid"><article class="panel-card"><span class="eyebrow">Prioridad comercial</span><h2>Clientes para revisar</h2>${state.crm.clients.map((client) => { const status = trafficLight(client); return `<div class="mini-alert ${status.color}"><b>${escapeHtml(client.name)}</b><span>${escapeHtml(status.next)}</span></div>`; }).join('') || '<p>No hay clientes.</p>'}</article><article class="panel-card"><span class="eyebrow">Actividad</span><h2>Resumen</h2><p>${state.crm.properties.length} propiedades cargadas.</p><p>${state.crm.reminders.length} tareas pendientes.</p><p>${state.crm.fichas.length} fichas comerciales.</p></article></div>`;
}

export function renderClients(container: HTMLElement): void {
  container.innerHTML = `<div class="panel-heading"><div><span class="eyebrow">CRM / Leads</span><h2>Pipeline comercial</h2></div><button data-toggle="client-form">Nuevo cliente</button></div><form id="client-form" class="data-form ${state.openForms.client ? '' : 'collapsed'}"><input name="name" placeholder="Nombre" required><input name="phone" placeholder="Teléfono" required><input name="email" type="email" placeholder="Email"><input name="interest" placeholder="Qué busca / zona" required><select name="status"><option>Lead</option><option>Cliente</option><option>Seguimiento</option><option>Cerrado</option></select><select name="temperature"><option>Caliente</option><option>Tibio</option><option>Frío</option></select><select name="pipeline"><option>Nuevo</option><option>Contactado</option><option>Calificado</option><option>Visita posible</option><option>Negociación</option><option>Cerrado</option><option>Perdido</option></select><input name="lastContact" type="date"><input name="nextFollowUp" type="date"><input name="budget" placeholder="Presupuesto"><input name="paymentMethod" placeholder="Forma de pago"><input name="purchaseTimeframe" placeholder="Plazo de compra"><select name="purpose"><option>Vivir</option><option>Invertir</option></select><select name="knowsArea"><option>Sí</option><option>No</option></select><select name="canMoveForward"><option>Sí</option><option>No</option></select><input name="objections" placeholder="Objeciones"><textarea name="notes" placeholder="Observaciones"></textarea><button type="submit">Guardar cliente</button></form><div class="card-list">${state.crm.clients.map((client) => { const status = trafficLight(client); return `<article class="crm-card ${status.color}"><div><div class="card-title"><h3>${escapeHtml(client.name)}</h3><span class="traffic ${status.color}">${escapeHtml(status.label)}</span></div><p>${escapeHtml(client.interest)}</p><small>${escapeHtml(client.phone)} · ${escapeHtml(client.budget || 'Sin presupuesto')}</small><strong class="next-step">${escapeHtml(status.next)}</strong></div><button class="delete" data-delete="clients" data-id="${client.id}">×</button></article>`; }).join('') || '<p class="empty-state">No hay clientes.</p>'}</div>`;
  document.querySelector<HTMLFormElement>('#client-form')?.addEventListener('submit', (event) => {
    event.preventDefault(); const values = formValues(event.currentTarget as HTMLFormElement);
    state.crm.clients.push({ id: nextId(state.crm.clients), name: field(values, 'name'), phone: field(values, 'phone'), email: field(values, 'email'), interest: field(values, 'interest'), status: field(values, 'status'), temperature: field(values, 'temperature') as Temperature, pipeline: field(values, 'pipeline'), lastContact: field(values, 'lastContact'), nextFollowUp: field(values, 'nextFollowUp'), budget: field(values, 'budget'), paymentMethod: field(values, 'paymentMethod'), purchaseTimeframe: field(values, 'purchaseTimeframe'), purpose: field(values, 'purpose'), knowsArea: field(values, 'knowsArea'), canMoveForward: field(values, 'canMoveForward'), objections: field(values, 'objections'), notes: field(values, 'notes') });
    state.openForms.client = false; saveData(); document.dispatchEvent(new CustomEvent('trv-render'));
  });
}

export function renderProperties(container: HTMLElement): void {
  container.innerHTML = `<div class="panel-heading"><div><span class="eyebrow">Propiedades</span><h2>Inventario activo</h2></div><button data-toggle="property-form">Nueva propiedad</button></div><form id="property-form" class="data-form ${state.openForms.property ? '' : 'collapsed'}"><input name="title" placeholder="Nombre" required><input name="address" placeholder="Zona o dirección" required><select name="type"><option>Departamento</option><option>Casa</option><option>Terreno</option><option>Comercial</option></select><select name="operation"><option>Venta</option><option>Captación</option></select><input name="price" type="number" min="0" placeholder="Precio" required><input name="owner" placeholder="Propietario o colega" required><select name="status"><option>Activa</option><option>Captación</option><option>Reservada</option><option>Cerrada</option></select><button type="submit">Guardar propiedad</button></form><div class="property-board">${state.crm.properties.map((property) => `<article class="property-card"><div><span>${escapeHtml(property.status)}</span><h3>${escapeHtml(property.title)}</h3><p>${escapeHtml(property.address)} · ${escapeHtml(property.type)}</p><strong>USD ${new Intl.NumberFormat('es-AR').format(property.price)}</strong></div><button class="delete" data-delete="properties" data-id="${property.id}">×</button></article>`).join('') || '<p class="empty-state">No hay propiedades.</p>'}</div>`;
  document.querySelector<HTMLFormElement>('#property-form')?.addEventListener('submit', (event) => {
    event.preventDefault(); const values = formValues(event.currentTarget as HTMLFormElement);
    state.crm.properties.push({ id: nextId(state.crm.properties), title: field(values, 'title'), address: field(values, 'address'), type: field(values, 'type'), operation: field(values, 'operation'), price: Number(field(values, 'price')), owner: field(values, 'owner'), status: field(values, 'status') });
    state.openForms.property = false; saveData(); document.dispatchEvent(new CustomEvent('trv-render'));
  });
}
