import type { Client, OfferCurrency, Property, Reservation, ReservationStatus } from './models.js';
import { saveData, state } from './store.js';
import { activeMember, visibleProperties } from './team-access.js';
import { assignmentVisible } from './team-policy.js';
import { escapeHtml } from './utils.js';
import { localIsoDate } from './lead-pipeline.js';
import { registerReservation, reservationsForClient, updateReservationStatus } from './reservation-workflow.js';

const SECTION = '[data-lead-reservations]'; let queued = false; let observing = false;
const money = new Intl.NumberFormat('es-AR', { maximumFractionDigits: 2 });
function label(property: Property | undefined, id: number): string { return property?.title?.trim() || property?.address?.trim() || `Propiedad #${id}`; }
function visibleReservations(clientId: number): Reservation[] { const actor = activeMember(); return reservationsForClient(state.crm.reservations.filter((x) => assignmentVisible(actor.role, actor.id, x.assignedToId)), clientId); }
function propertyOptions(): string { return visibleProperties().slice().sort((a,b)=>label(a,a.id).localeCompare(label(b,b.id),'es')).map((x)=>`<option value="${x.id}">${escapeHtml(label(x,x.id))}</option>`).join(''); }
function offerOptions(clientId: number): string { const actor=activeMember(); return state.crm.offers.filter((x)=>x.clientId===clientId&&assignmentVisible(actor.role,actor.id,x.assignedToId)).map((x)=>`<option value="${x.id}" data-property-id="${x.propertyId}">#${x.id} · ${escapeHtml(x.currency)} ${escapeHtml(money.format(x.amount))} · ${escapeHtml(x.status)}</option>`).join(''); }
function form(client: Client): string { return `<form class="pc-reservation-form" data-register-reservation="${client.id}"><label>Propiedad *<select name="propertyId" required><option value="">Seleccionar propiedad</option>${propertyOptions()}</select></label><label>Oferta vinculada (opcional)<select name="offerId"><option value="">Sin oferta vinculada</option>${offerOptions(client.id)}</select></label><div class="pc-reservation-pair"><label>Monto *<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label><label>Moneda *<select name="currency" required><option>USD</option><option>ARS</option></select></label></div><label>Forma de pago<input name="paymentMethod" maxlength="160" placeholder="Opcional"></label><label>Condiciones<textarea name="conditions" rows="2" maxlength="280" placeholder="Opcional"></textarea></label><div class="pc-reservation-pair"><label>Fecha de reserva *<input name="reservedAt" type="date" value="${localIsoDate()}" required></label><label>Vencimiento<input name="expiresAt" type="date"></label></div><p class="pc-reservation-error" data-reservation-error role="alert" hidden></p><button type="submit">Guardar reserva</button></form>`; }
function statusClass(value: ReservationStatus): string { return value.toLowerCase(); }
function row(item: Reservation): string { const property=state.crm.properties.find((x)=>x.id===item.propertyId); const offer=item.offerId?state.crm.offers.find((x)=>x.id===item.offerId):undefined; return `<article class="pc-reservation-row" data-reservation-id="${item.id}"><div class="pc-reservation-row-head"><strong>${escapeHtml(label(property,item.propertyId))}</strong><span class="pc-reservation-status status-${statusClass(item.status)}">${escapeHtml(item.status)}</span></div><div class="pc-reservation-primary"><strong>${escapeHtml(item.currency)} ${escapeHtml(money.format(item.amount))}</strong><span>Reserva: ${escapeHtml(item.reservedAt)}${item.expiresAt?` · Vence: ${escapeHtml(item.expiresAt)}`:''}</span></div>${item.offerId?`<p class="pc-reservation-link">Oferta vinculada: #${item.offerId}${offer?` · ${escapeHtml(offer.status)}`:''}</p>`:''}${item.paymentMethod?`<p><b>Pago:</b> ${escapeHtml(item.paymentMethod)}</p>`:''}${item.conditions?`<p><b>Condiciones:</b> ${escapeHtml(item.conditions)}</p>`:''}${item.status==='Activa'?`<form class="pc-reservation-status-form" data-update-reservation="${item.id}"><label>Estado<select name="status" required><option value="">Cambiar estado</option><option value="Cancelada">Cancelada</option><option value="Concretada">Concretada</option></select></label><p class="pc-reservation-error" data-reservation-error role="alert" hidden></p><button type="submit">Guardar estado</button></form>`:''}</article>`; }
function section(client: Client): string { const items=visibleReservations(client.id); const register=propertyOptions()?`<details class="pc-reservation-disclosure" data-reservation-disclosure><summary>Registrar reserva</summary><div data-reservation-form-host></div></details>`:'<span class="pc-reservation-empty">Sin propiedades visibles</span>'; return `<section class="pc-lead-reservations" data-lead-reservations="${client.id}" aria-label="Reservas de ${escapeHtml(client.name)}"><div class="pc-lead-reservations-head"><div><strong>Reservas</strong><span>${items.length?`${items.length} ${items.length===1?'reserva':'reservas'}`:'Sin reservas registradas'}</span></div>${register}</div>${items.length?`<div class="pc-reservation-list">${items.map(row).join('')}</div>`:'<p class="pc-reservation-empty">Todavía no hay reservas para este lead.</p>'}</section>`; }
function insert(card: HTMLElement, client: Client): void { const host=card.querySelector<HTMLElement>('.mvp-lead-full-content'); if(!host)return; const wrapper=document.createElement('div');wrapper.innerHTML=section(client);const el=wrapper.firstElementChild;if(!(el instanceof HTMLElement))return;const current=card.querySelector<HTMLElement>(SECTION);if(current)current.replaceWith(el);else{const offers=host.querySelector('[data-lead-offers]');const anchor=offers?.nextSibling??host.querySelector('.mvp-lead-history, .mvp-lead-matches, .mvp-lead-full-actions');host.insertBefore(el,anchor);}const details=el.querySelector<HTMLDetailsElement>('[data-reservation-disclosure]');details?.addEventListener('toggle',()=>{const target=details.querySelector<HTMLElement>('[data-reservation-form-host]');if(target)target.innerHTML=details.open?form(client):'';}); }
export function enhanceLeadReservations(): void { document.querySelectorAll<HTMLElement>('.mvp-lead-card[data-client-id]').forEach((card)=>{const client=state.crm.clients.find((x)=>x.id===Number(card.dataset.clientId));if(client)insert(card,client);}); }
function queue():void{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhanceLeadReservations();});}
function busy(form:HTMLFormElement,value:boolean):void{form.dataset.submitting=value?'true':'false';form.querySelectorAll<HTMLButtonElement>('button[type=submit]').forEach((x)=>{x.disabled=value;});}
function error(form:HTMLFormElement,value:unknown):void{const out=form.querySelector<HTMLElement>('[data-reservation-error]');if(out){out.textContent=value instanceof Error?value.message:'No se pudo guardar la reserva.';out.hidden=false;}}
function actor(){const x=activeMember();return{id:x.id,role:x.role};}
function apply(result:{crm:typeof state.crm}):void{state.crm=result.crm;saveData('Flujo comercial de reservas');document.dispatchEvent(new CustomEvent('trv-render'));}
document.addEventListener('submit',(event)=>{const target=event.target;if(!(target instanceof HTMLFormElement))return;if(!target.matches('[data-register-reservation],[data-update-reservation]'))return;event.preventDefault();if(target.dataset.submitting==='true')return;busy(target,true);try{const data=new FormData(target);if(target.matches('[data-register-reservation]')){const rawOffer=String(data.get('offerId')||'');apply(registerReservation(state.crm,actor(),{clientId:Number(target.dataset.registerReservation),propertyId:Number(data.get('propertyId')),offerId:rawOffer?Number(rawOffer):undefined,amount:Number(data.get('amount')),currency:String(data.get('currency')||'') as OfferCurrency,paymentMethod:String(data.get('paymentMethod')||''),conditions:String(data.get('conditions')||''),reservedAt:String(data.get('reservedAt')||''),expiresAt:String(data.get('expiresAt')||'')}));}else{apply(updateReservationStatus(state.crm,actor(),{reservationId:Number(target.dataset.updateReservation),status:String(data.get('status')||'')}));}}catch(value){busy(target,false);error(target,value);}});
document.addEventListener('change',(event)=>{const offer=(event.target as HTMLElement).closest<HTMLSelectElement>('[data-register-reservation] select[name="offerId"]');if(!offer?.value)return;const option=offer.selectedOptions[0];const property=offer.form?.elements.namedItem('propertyId');if(property instanceof HTMLSelectElement&&option?.dataset.propertyId)property.value=option.dataset.propertyId;});
document.addEventListener('trv-render',queue);function observe():void{if(observing)return;const root=document.querySelector('#root');if(!root)return;observing=true;new MutationObserver(queue).observe(root,{childList:true,subtree:true});}observe();queue();
